INSERT INTO TB_ENDERECO VALUES (1, 'RUA CEARÁ');
INSERT INTO TB_ENDERECO VALUES (2, 'RUA BAHIA');
INSERT INTO TB_ENDERECO VALUES (3, 'RUA MINAS GERAIS');
INSERT INTO TB_ENDERECO VALUES (4, 'RUA PIAUÍ');
INSERT INTO TB_ENDERECO VALUES (5, 'RUA ARAXA');
INSERT INTO TB_ENDERECO VALUES (6, 'RUA SÃO PAULO');
INSERT INTO TB_ENDERECO VALUES (7, 'RUA BELO HORIZONTE');
INSERT INTO TB_ENDERECO VALUES (8, 'RUA CAMPINA GRANDE');


INSERT INTO TB_BAIRRO VALUES(1, 'CONDÁ');
INSERT INTO TB_BAIRRO VALUES(2, 'CENTRO');
INSERT INTO TB_BAIRRO VALUES(3, 'BELO HORIZONTE');
INSERT INTO TB_BAIRRO VALUES(4, 'PARQUE VERDE');
INSERT INTO TB_BAIRRO VALUES(5, 'ANA CLARA');
INSERT INTO TB_BAIRRO VALUES(6, 'INDEPENDÊNCIA');
INSERT INTO TB_BAIRRO VALUES(7, 'NAZARÉ');
INSERT INTO TB_BAIRRO VALUES(8, 'JOAQUINA');

INSERT INTO TB_CIDADE VALUES(1, 'MEDIANEIRA');
INSERT INTO TB_CIDADE VALUES(2, 'SÃO MIGUEL');
INSERT INTO TB_CIDADE VALUES(3, 'MATELÂNDIA');
INSERT INTO TB_CIDADE VALUES(4, 'CASCAVEL');
INSERT INTO TB_CIDADE VALUES(5, 'FOZ DO IGUAÇU');
INSERT INTO TB_CIDADE VALUES(6, 'TOLEDO');
INSERT INTO TB_CIDADE VALUES(7, 'MARIPÁ');
INSERT INTO TB_CIDADE VALUES(8, 'SANTA HELENA');

INSERT INTO TB_TIPO VALUES(1, 'MOBILIA');
INSERT INTO TB_TIPO VALUES(2, 'VEÍCULO');
INSERT INTO TB_TIPO VALUES(3, 'INFORMÁTICA');
INSERT INTO TB_TIPO VALUES(4, 'ELETRONICO');

INSERT INTO TB_DEPARTAMENTO VALUES (1, 'FINANCEIRO');
INSERT INTO TB_DEPARTAMENTO VALUES (2, 'CONTABILIDADE');
INSERT INTO TB_DEPARTAMENTO VALUES (3, 'MANUTENÇÃO');
INSERT INTO TB_DEPARTAMENTO VALUES (4, 'INFORMÁTICA');


INSERT INTO TB_MARCA VALUES (1, 'VALITA');
INSERT INTO TB_MARCA VALUES (2, 'FORD');
INSERT INTO TB_MARCA VALUES (3, 'WOLKS');
INSERT INTO TB_MARCA VALUES (4, 'ESCRIMAC');
INSERT INTO TB_MARCA VALUES (5, 'INTEL');


INSERT INTO TB_PREDIO (PRE_CODIGO, PRE_DESCRICAO, PRE_CODENDERECO, PRE_NUMERO, PRE_CODBAIRRO, PRE_CODCIDADE)
               VALUES (1, 'PRÉDIO JOÃO AVELINO', 2, 1500, 3, 1);

INSERT INTO TB_PREDIO (PRE_CODIGO, PRE_DESCRICAO, PRE_CODENDERECO, PRE_NUMERO, PRE_CODBAIRRO, PRE_CODCIDADE)
               VALUES (2, 'PRÉDIO SÃO JOSÉ', 1, 200, 4, 1);

INSERT INTO TB_PREDIO (PRE_CODIGO, PRE_DESCRICAO, PRE_CODENDERECO, PRE_NUMERO, PRE_CODBAIRRO, PRE_CODCIDADE)
               VALUES (3, 'PRÉDIO CENTRO TOLEDO', 5, 342, 2, 6);

INSERT INTO TB_PREDIO (PRE_CODIGO, PRE_DESCRICAO, PRE_CODENDERECO, PRE_NUMERO, PRE_CODBAIRRO, PRE_CODCIDADE)
               VALUES (4, 'INSS', 6, 3455, 5, 5);

INSERT INTO TB_PREDIO (PRE_CODIGO, PRE_DESCRICAO, PRE_CODENDERECO, PRE_NUMERO, PRE_CODBAIRRO, PRE_CODCIDADE)
               VALUES (5, 'PRÉDIO ANTONIO PRADO', 7, 1000, 6, 4);

INSERT INTO TB_PREDIO (PRE_CODIGO, PRE_DESCRICAO, PRE_CODENDERECO, PRE_NUMERO, PRE_CODBAIRRO, PRE_CODCIDADE)
               VALUES (6, 'PRÉDIO SÃO LEOPOLDO', 7, 10001, 2, 5);